openapi: 3.0.1
info:
  title: User API
  description: An API used for user authentification
  version: v1
paths:
  '/ChatHistory/Get/{chatroom}':
    get:
      tags:
        - ChatHistory
      parameters:
        - name: chatroom
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChatMessage'
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessage'
            text/json:
              schema:
                $ref: '#/components/schemas/ChatMessage'
components:
  schemas:
    ChatMessage:
      type: object
      properties:
        id:
          type: integer
          format: int32
        message:
          type: string
          nullable: true
        user:
          type: string
          nullable: true
        chatRoom:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false