openapi: 3.0.1
info:
  title: Event API
  description: An API used for event management
  version: v1
paths:
  /Event/GetEventByID:
    get:
      tags:
        - Event
      parameters:
        - name: Id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /Event/GetAllEvents:
    get:
      tags:
        - Event
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /Event/GetEventsByInterest:
    get:
      tags:
        - Event
      parameters:
        - name: interestId
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
  /Event/GetEventsByInterests:
    get:
      tags:
        - Event
      parameters:
        - name: ids
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
  /Event/GetEventByLocation:
    get:
      tags:
        - Event
      parameters:
        - name: latitude
          in: query
          description: Desired latitude in degrees
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          description: Desired longitude in degrees
          schema:
            type: number
            format: double
        - name: radius
          in: query
          description: Radius included results in KM
          schema:
            type: number
            format: double
            default: 20
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /Event/UpdateEvent:
    put:
      tags:
        - Event
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            format: int32
        - name: title
          in: query
          schema:
            type: string
        - name: description
          in: query
          schema:
            type: string
        - name: locationbased
          in: query
          schema:
            type: boolean
        - name: latitude
          in: query
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          schema:
            type: number
            format: double
        - name: maxpeople
          in: query
          schema:
            type: integer
            format: int32
        - name: minpeople
          in: query
          schema:
            type: integer
            format: int32
        - name: startevent
          in: query
          schema:
            type: string
            format: date-time
        - name: hasstarted
          in: query
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
          text/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
          application/*+json:
            schema:
              type: array
              items:
                type: integer
                format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /Event/DeleteEvent:
    delete:
      tags:
        - Event
      parameters:
        - name: Id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /Event/CreateEvent:
    post:
      tags:
        - Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/EventDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/EventDTO'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EventDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    EventDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        interests:
          uniqueItems: true
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        members:
          uniqueItems: true
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        title:
          type: string
          nullable: true
        locationBased:
          type: boolean
          nullable: true
        latitude:
          type: number
          format: double
          nullable: true
        longitude:
          type: number
          format: double
          nullable: true
        hostID:
          type: integer
          format: int32
        maxPeople:
          type: integer
          format: int32
          nullable: true
        minPeople:
          type: integer
          format: int32
          nullable: true
        startEvent:
          type: string
          format: date-time
        hasStarted:
          type: boolean
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }